version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: spa-template-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spa_template
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: spa-template-server
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/spa_template
      - NODE_ENV=development
      - PORT=8000
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRES_IN=7d
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: spa-template-client
    environment:
      - VITE_API_URL=http://localhost:8000/api
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  postgres_data: